server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DiabloElf/spring-boot-configs.git
          default-label: master
          skip-ssl-validation: true
          search-paths: "{application}"
